News Article Extractor: DBWriter.DBWriter.DBWriter Class Reference
DBWriter.DBWriter.DBWriter Class Reference
Public Member Functions
def __init__ (self, multiprocessing.Queue inQueue, configparser.ConfigParser inConfigObject)
def __del__ (self)
def WriteEntries (self, ExtractedArticle inArticleObject)
def run (self)
Public Attributes
good
Detailed Description
This class is responsible for checking the global queue for objects.  If any have been placed, it will then write
them to the database.  It runs in it's own process.
Definition at line 16 of file DBWriter.py.
Constructor & Destructor Documentation
__init__()
def DBWriter.DBWriter.DBWriter.__init__ (self, multiprocessing.Queue inQueue, configparser.ConfigParser inConfigObject)
Perform our specific setup
:param inQueue: multiprocessing.Queue object to read from
Definition at line 23 of file DBWriter.py.
     def __init__(self, inQueue: multiprocessing.Queue, inConfigObject: configparser.ConfigParser):
         """
         Perform our specific setup
         :param inQueue: multiprocessing.Queue object to read from
         """
         try:
             multiprocessing.Process.__init__(self, group=None)
             # Flag to check if we created OK.
             self.good = True
             # Save the global queue
             if not inQueue:
                 self.good = False
                 # Don't bother running if we don't have a Queue object passed in
                 return
             self._queue = inQueue
             # DB Parameters
             self._DBHost = str()
             self._DBPort = str()
             self._DBUser = str()
             self._DBPassword = str()
             self._DBTable = str()
             # DB Objects
             self._DBConnection = None
             self._DBCursor = None
             # Read the configuration
             if not self._ReadConfiguration(inConfigObject):
                 self.good = False
                 # If we can't read the full configuration, then no need to continue
                 return
             # Create the database object and cursor
             if not self._CreateDBObjects():
                 self.good = False
                 # If we can't create the DB connection, no need to continue
                 return
         except Exception as e:
             print("Exception in DBWriter::__init__: {}".format(e))
             self.good = False
__del__()
def DBWriter.DBWriter.DBWriter.__del__ (self)
Clean up after ourselves
:return: None
Definition at line 74 of file DBWriter.py.
     def __del__(self):
         """
         Clean up after ourselves
         :return: None
         """
         try:
             # In case we have any commits outstanding.
             if self._DBConnection:
                 self._DBConnection.commit()
             # Now close out
             if self._DBCursor:
                 self._DBCursor.close()
             # No need to check here, if it's None the except will catch and ignore
             self._DBConnection.close()
         except Exception as e:
             print("Exception in DBWriter::__del__: {}".format(e))
References DBWriter.DBWriter.DBWriter._DBConnection, DBWriter.DBWriter.DBWriter._DBCursor, DBWriter.DBWriter.DBWriter._DBHost, DBWriter.DBWriter.DBWriter._DBPassword, DBWriter.DBWriter.DBWriter._DBPort, DBWriter.DBWriter.DBWriter._DBTable, DBWriter.DBWriter.DBWriter._DBUser, DBWriter.DBWriter.DBWriter._FindCountries(), DBWriter.DBWriter.DBWriter._GetUniqueCommon(), DBWriter.DBWriter.DBWriter._InsertArticleEvents(), DBWriter.DBWriter.DBWriter._InsertArticleFacilities(), DBWriter.DBWriter.DBWriter._InsertArticleLocations(), DBWriter.DBWriter.DBWriter._InsertArticleOrganizations(), DBWriter.DBWriter.DBWriter._InsertArticlePeople(), DBWriter.DBWriter.DBWriter._InsertEvent(), DBWriter.DBWriter.DBWriter._InsertFacility(), DBWriter.DBWriter.DBWriter._InsertLocation(), DBWriter.DBWriter.DBWriter._InsertOrganization(), DBWriter.DBWriter.DBWriter._InsertPerson(), DBWriter.DBWriter.DBWriter._LocationCaseThree(), DBWriter.DBWriter.DBWriter._LocationCaseTwo(), DBWriter.DBWriter.DBWriter._ResetSQLConnection(), and DBWriter.DBWriter.DBWriter.good.
Member Function Documentation
run()
def DBWriter.DBWriter.DBWriter.run (self)
Override to handle the main loop of the process
:return:
Definition at line 653 of file DBWriter.py.
     def run(self):
         """
         Override to handle the main loop of the process
         :return:
         """
         continueFlag = True
         while continueFlag:
             articleObject = self._queue.get()
             # Check for our poison pill
             if articleObject.articleText == "EXITCALLED":
                 continueFlag = False
                 continue
             self.WriteEntries(articleObject)
References DBWriter.DBWriter.DBWriter._DBConnection, DBWriter.DBWriter.DBWriter._DBCursor, DBWriter.DBWriter.DBWriter._InsertArticleLocations(), DBWriter.DBWriter.DBWriter._queue, DBWriter.DBWriter.DBWriter._ResetSQLConnection(), and DBWriter.DBWriter.DBWriter.WriteEntries().
WriteEntries()
def DBWriter.DBWriter.DBWriter.WriteEntries (self, ExtractedArticle inArticleObject)
This is the main part of the thread that pulls from the global queue and then writes it into the database
:return:
Definition at line 608 of file DBWriter.py.
     def WriteEntries(self, inArticleObject: ExtractedArticle):
         """
         This is the main part of the thread that pulls from the global queue and then writes it into the database
         :return:
         """
         try:
             # Push the article metadata to the DB and get the assigned identifier for it.
             print("""
                  INSERT INTO news_articles (article_title, article_url, article_text, website)
                  VALUES ({}, {}, {}, {}) RETURNING id;
                  """.format(inArticleObject.articleTitle, inArticleObject.articleURL, inArticleObject.articleText,
                             inArticleObject.website))
             self._DBCursor.execute("""
                                     INSERT INTO news_articles (article_title, article_url, article_text, website)
                                     VALUES (%s, %s, %s, %s) RETURNING id;
                                     """,
                                    (inArticleObject.articleTitle, inArticleObject.articleURL,
                                      inArticleObject.articleText, inArticleObject.website))
             self._DBConnection.commit()
             # Get the ID of the inserted object
             articleID = self._DBCursor.fetchone()[0]
             # Now populate the article_people table
             self._ProcessPeople(articleID, inArticleObject.people)
             # Now populate the article_facilities table
             self._ProcessFacilities(articleID, inArticleObject.facilities)
             # Now populate the article_organizations table
             self._ProcessOrganizations(articleID, inArticleObject.organizations)
             # Now populate the article_events table
             self._ProcessEvents(articleID, inArticleObject.events)
             # Now populate the article_locations table
             self._ProcessLocations(articleID, inArticleObject.locations)
         except Exception as e:
             print("Exception in DBWriter::WriteEntries: {}".format(e))
             self.good = False
             self._ResetSQLConnection()
References DBWriter.DBWriter.DBWriter._DBConnection, DBWriter.DBWriter.DBWriter._DBCursor, DBWriter.DBWriter.DBWriter._ProcessEvents(), DBWriter.DBWriter.DBWriter._ProcessFacilities(), DBWriter.DBWriter.DBWriter._ProcessLocations(), DBWriter.DBWriter.DBWriter._ProcessOrganizations(), DBWriter.DBWriter.DBWriter._ProcessPeople(), DBWriter.DBWriter.DBWriter._ResetSQLConnection(), and DBWriter.DBWriter.DBWriter.good.
Referenced by DBWriter.DBWriter.DBWriter.run().
Member Data Documentation
good
DBWriter.DBWriter.DBWriter.good
Definition at line 33 of file DBWriter.py.
Referenced by DBWriter.DBWriter.DBWriter.__del__(), websites.WebsiteBase.WebsiteBase.__del__(), and DBWriter.DBWriter.DBWriter.WriteEntries().
The documentation for this class was generated from the following file:
DBWriter/DBWriter.py